# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/fpga/ddc/ddc.srcs/sources_1/bd/ddc/ip/ddc_zynq_ultra_ps_e_0_0/ddc_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'ddc_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/fpga/ddc/ddc.gen/sources_1/bd/ddc/ip/ddc_zynq_ultra_ps_e_0_0/ddc_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddc_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/fpga/ddc/ddc.gen/sources_1/bd/ddc/ip/ddc_zynq_ultra_ps_e_0_0/ddc_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddc_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/fpga/ddc/ddc.srcs/sources_1/bd/ddc/ip/ddc_zynq_ultra_ps_e_0_0/ddc_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'ddc_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/fpga/ddc/ddc.gen/sources_1/bd/ddc/ip/ddc_zynq_ultra_ps_e_0_0/ddc_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddc_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/fpga/ddc/ddc.gen/sources_1/bd/ddc/ip/ddc_zynq_ultra_ps_e_0_0/ddc_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddc_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
