# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/duc/duc.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc || ORIG_REF_NAME==duc} -quiet] -quiet

# IP: bd/duc/ip/duc_zynq_ultra_ps_e_0_0/duc_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==duc_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/duc/ip/duc_proc_sys_reset_0_0/duc_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_proc_sys_reset_0_0 || ORIG_REF_NAME==duc_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/duc/ip/duc_smartconnect_0_0/duc_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_smartconnect_0_0 || ORIG_REF_NAME==duc_smartconnect_0_0} -quiet] -quiet

# Block Designs: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/bd_a4af.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_0/bd_a4af_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_1/bd_a4af_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_2/bd_a4af_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_3/bd_a4af_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_4/bd_a4af_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_5/bd_a4af_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_6/bd_a4af_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_7/bd_a4af_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_8/bd_a4af_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_9/bd_a4af_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_10/bd_a4af_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_11/bd_a4af_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_12/bd_a4af_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_13/bd_a4af_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_14/bd_a4af_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_15/bd_a4af_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_16/bd_a4af_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_17/bd_a4af_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_18/bd_a4af_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_19/bd_a4af_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_20/bd_a4af_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_21/bd_a4af_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_22/bd_a4af_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_23/bd_a4af_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_24/bd_a4af_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_25/bd_a4af_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_26/bd_a4af_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_27/bd_a4af_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_28/bd_a4af_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_29/bd_a4af_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_30/bd_a4af_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_31/bd_a4af_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_32/bd_a4af_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_33/bd_a4af_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_34/bd_a4af_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_35/bd_a4af_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_36/bd_a4af_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_37/bd_a4af_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_38/bd_a4af_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_39/bd_a4af_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_40/bd_a4af_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_41/bd_a4af_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_42/bd_a4af_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/duc/ip/duc_axi_bram_ctrl_0_0/duc_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_axi_bram_ctrl_0_0 || ORIG_REF_NAME==duc_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/duc/ip/duc_blk_mem_gen_0_0/duc_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_blk_mem_gen_0_0 || ORIG_REF_NAME==duc_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/duc/ip/duc_axi_dma_0_0/duc_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_axi_dma_0_0 || ORIG_REF_NAME==duc_axi_dma_0_0} -quiet] -quiet

# IP: bd/duc/ip/duc_ila_0_0/duc_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_ila_0_0 || ORIG_REF_NAME==duc_ila_0_0} -quiet] -quiet

# IP: bd/duc/ip/duc_ila_0_1/duc_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_ila_0_1 || ORIG_REF_NAME==duc_ila_0_1} -quiet] -quiet

# IP: bd/duc/ip/duc_ila_0_2/duc_ila_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_ila_0_2 || ORIG_REF_NAME==duc_ila_0_2} -quiet] -quiet

# IP: bd/duc/ip/duc_ila_0_3/duc_ila_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_ila_0_3 || ORIG_REF_NAME==duc_ila_0_3} -quiet] -quiet

# IP: bd/duc/ip/duc_axis_upsample_0_0/duc_axis_upsample_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_axis_upsample_0_0 || ORIG_REF_NAME==duc_axis_upsample_0_0} -quiet] -quiet

# IP: bd/duc/ip/duc_axis_upsample_0_1/duc_axis_upsample_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_axis_upsample_0_1 || ORIG_REF_NAME==duc_axis_upsample_0_1} -quiet] -quiet

# IP: bd/duc/ip/duc_ila_0_4/duc_ila_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_ila_0_4 || ORIG_REF_NAME==duc_ila_0_4} -quiet] -quiet

# IP: bd/duc/ip/duc_halfband_fir_0_0/duc_halfband_fir_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_halfband_fir_0_0 || ORIG_REF_NAME==duc_halfband_fir_0_0} -quiet] -quiet

# IP: bd/duc/ip/duc_halfband_fir_0_1/duc_halfband_fir_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_halfband_fir_0_1 || ORIG_REF_NAME==duc_halfband_fir_0_1} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_zynq_ultra_ps_e_0_0/duc_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_zynq_ultra_ps_e_0_0/duc_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==duc_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==duc_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_proc_sys_reset_0_0/duc_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==duc_proc_sys_reset_0_0 || ORIG_REF_NAME==duc_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_proc_sys_reset_0_0/duc_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==duc_proc_sys_reset_0_0 || ORIG_REF_NAME==duc_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_1/bd_a4af_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_1/bd_a4af_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_2/bd_a4af_arsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_3/bd_a4af_rsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_4/bd_a4af_awsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_5/bd_a4af_wsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_6/bd_a4af_bsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_10/bd_a4af_s00a2s_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_11/bd_a4af_sarn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_12/bd_a4af_srn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_13/bd_a4af_sawn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_14/bd_a4af_swn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_15/bd_a4af_sbn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_19/bd_a4af_s01a2s_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_20/bd_a4af_sarn_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_21/bd_a4af_srn_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_25/bd_a4af_s02a2s_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_26/bd_a4af_sawn_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_27/bd_a4af_swn_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_28/bd_a4af_sbn_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_29/bd_a4af_m00s2a_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_30/bd_a4af_m00arn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_31/bd_a4af_m00rn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_32/bd_a4af_m00awn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_33/bd_a4af_m00wn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_34/bd_a4af_m00bn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_36/bd_a4af_m01s2a_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_37/bd_a4af_m01arn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_38/bd_a4af_m01rn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_39/bd_a4af_m01awn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_40/bd_a4af_m01wn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/bd_0/ip/ip_41/bd_a4af_m01bn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_smartconnect_0_0/ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_blk_mem_gen_0_0/duc_blk_mem_gen_0_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_axi_dma_0_0/duc_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==duc_axi_dma_0_0 || ORIG_REF_NAME==duc_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_axi_dma_0_0/duc_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==duc_axi_dma_0_0 || ORIG_REF_NAME==duc_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==duc_ila_0_0 || ORIG_REF_NAME==duc_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==duc_ila_0_0 || ORIG_REF_NAME==duc_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_ila_0_0/duc_ila_0_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==duc_ila_0_1 || ORIG_REF_NAME==duc_ila_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_ila_0_1/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==duc_ila_0_1 || ORIG_REF_NAME==duc_ila_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_ila_0_1/duc_ila_0_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_ila_0_2/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==duc_ila_0_2 || ORIG_REF_NAME==duc_ila_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_ila_0_2/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==duc_ila_0_2 || ORIG_REF_NAME==duc_ila_0_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_ila_0_2/duc_ila_0_2_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_ila_0_3/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==duc_ila_0_3 || ORIG_REF_NAME==duc_ila_0_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_ila_0_3/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==duc_ila_0_3 || ORIG_REF_NAME==duc_ila_0_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_ila_0_3/duc_ila_0_3_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_ila_0_4/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==duc_ila_0_4 || ORIG_REF_NAME==duc_ila_0_4} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_ila_0_4/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==duc_ila_0_4 || ORIG_REF_NAME==duc_ila_0_4} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/ip/duc_ila_0_4/duc_ila_0_4_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/bd/duc/duc_ooc.xdc
