# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/duc_cfr/duc_cfr.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr || ORIG_REF_NAME==duc_cfr} -quiet] -quiet

# IP: bd/duc_cfr/ip/duc_cfr_axi_bram_ctrl_0_0/duc_cfr_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_axi_bram_ctrl_0_0 || ORIG_REF_NAME==duc_cfr_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/duc_cfr/ip/duc_cfr_axi_dma_0_0/duc_cfr_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_axi_dma_0_0 || ORIG_REF_NAME==duc_cfr_axi_dma_0_0} -quiet] -quiet

# IP: bd/duc_cfr/ip/duc_cfr_axis_upsample_0_0/duc_cfr_axis_upsample_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_axis_upsample_0_0 || ORIG_REF_NAME==duc_cfr_axis_upsample_0_0} -quiet] -quiet

# IP: bd/duc_cfr/ip/duc_cfr_blk_mem_gen_0_0/duc_cfr_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_blk_mem_gen_0_0 || ORIG_REF_NAME==duc_cfr_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/duc_cfr/ip/duc_cfr_halfband_fir_0_0/duc_cfr_halfband_fir_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_halfband_fir_0_0 || ORIG_REF_NAME==duc_cfr_halfband_fir_0_0} -quiet] -quiet

# IP: bd/duc_cfr/ip/duc_cfr_proc_sys_reset_0_0/duc_cfr_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_proc_sys_reset_0_0 || ORIG_REF_NAME==duc_cfr_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/duc_cfr_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_smartconnect_0_0 || ORIG_REF_NAME==duc_cfr_smartconnect_0_0} -quiet] -quiet

# IP: bd/duc_cfr/ip/duc_cfr_zynq_ultra_ps_e_0_0/duc_cfr_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==duc_cfr_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/duc_cfr/ip/duc_cfr_cfr_0_0/duc_cfr_cfr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_cfr_0_0 || ORIG_REF_NAME==duc_cfr_cfr_0_0} -quiet] -quiet

# IP: bd/duc_cfr/ip/duc_cfr_halfband_fir_0_1/duc_cfr_halfband_fir_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_halfband_fir_0_1 || ORIG_REF_NAME==duc_cfr_halfband_fir_0_1} -quiet] -quiet

# IP: bd/duc_cfr/ip/duc_cfr_axis_upsample_0_1/duc_cfr_axis_upsample_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_axis_upsample_0_1 || ORIG_REF_NAME==duc_cfr_axis_upsample_0_1} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/duc_cfr_ooc.xdc
