# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/mixer_cmpy_0/mixer_cmpy_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_cmpy_0 || ORIG_REF_NAME==mixer_cmpy_0} -quiet] -quiet

# Block Designs: bd/mixer/mixer.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer || ORIG_REF_NAME==mixer} -quiet] -quiet

# IP: bd/mixer/ip/mixer_axi_bram_ctrl_0_0/mixer_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_axi_bram_ctrl_0_0 || ORIG_REF_NAME==mixer_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/mixer/ip/mixer_axi_dma_0_0/mixer_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_axi_dma_0_0 || ORIG_REF_NAME==mixer_axi_dma_0_0} -quiet] -quiet

# IP: bd/mixer/ip/mixer_axis_decimate2_0_0/mixer_axis_decimate2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_axis_decimate2_0_0 || ORIG_REF_NAME==mixer_axis_decimate2_0_0} -quiet] -quiet

# IP: bd/mixer/ip/mixer_axis_decimate2_1_0/mixer_axis_decimate2_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_axis_decimate2_1_0 || ORIG_REF_NAME==mixer_axis_decimate2_1_0} -quiet] -quiet

# IP: bd/mixer/ip/mixer_axis_halfband_fir_0_0/mixer_axis_halfband_fir_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_axis_halfband_fir_0_0 || ORIG_REF_NAME==mixer_axis_halfband_fir_0_0} -quiet] -quiet

# IP: bd/mixer/ip/mixer_axis_halfband_fir_1_0/mixer_axis_halfband_fir_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_axis_halfband_fir_1_0 || ORIG_REF_NAME==mixer_axis_halfband_fir_1_0} -quiet] -quiet

# IP: bd/mixer/ip/mixer_blk_mem_gen_0_0/mixer_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_blk_mem_gen_0_0 || ORIG_REF_NAME==mixer_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/mixer/ip/mixer_proc_sys_reset_0_0/mixer_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_proc_sys_reset_0_0 || ORIG_REF_NAME==mixer_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/mixer/ip/mixer_smartconnect_0_0/mixer_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_smartconnect_0_0 || ORIG_REF_NAME==mixer_smartconnect_0_0} -quiet] -quiet

# IP: bd/mixer/ip/mixer_zynq_ultra_ps_e_0_0/mixer_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==mixer_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/mixer/ip/mixer_axis_mixer_down_0_0/mixer_axis_mixer_down_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_axis_mixer_down_0_0 || ORIG_REF_NAME==mixer_axis_mixer_down_0_0} -quiet] -quiet

# IP: ip/mixer_cmpy_0/mixer_cmpy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_cmpy_0 || ORIG_REF_NAME==mixer_cmpy_0} -quiet] -quiet

# IP: bd/mixer/ip/mixer_system_ila_0_0/mixer_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_system_ila_0_0 || ORIG_REF_NAME==mixer_system_ila_0_0} -quiet] -quiet

# IP: bd/mixer/ip/mixer_system_ila_0_1/mixer_system_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_system_ila_0_1 || ORIG_REF_NAME==mixer_system_ila_0_1} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/mixer_ooc.xdc
