# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DPD/fpga/dpd.srcs/sources_1/bd/duc_cfr_dpd/ip/duc_cfr_dpd_cfr_0_0/duc_cfr_dpd_cfr_0_0.xci
# IP: The module: 'duc_cfr_dpd_cfr_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/q_scale/q_scale.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==q_scale || ORIG_REF_NAME==q_scale} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/i_scale/i_scale.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i_scale || ORIG_REF_NAME==i_scale} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/div_gen_0/div_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/cordic_0/cordic_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/cfr_qq/cfr_qq.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfr_qq || ORIG_REF_NAME==cfr_qq} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/cfr_ii/cfr_ii.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfr_ii || ORIG_REF_NAME==cfr_ii} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DPD/fpga/dpd.gen/sources_1/bd/duc_cfr_dpd/ip/duc_cfr_dpd_cfr_0_0/duc_cfr_dpd_cfr_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'duc_cfr_dpd_cfr_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DPD/fpga/dpd.srcs/sources_1/bd/duc_cfr_dpd/ip/duc_cfr_dpd_cfr_0_0/duc_cfr_dpd_cfr_0_0.xci
# IP: The module: 'duc_cfr_dpd_cfr_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/q_scale/q_scale.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==q_scale || ORIG_REF_NAME==q_scale} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/i_scale/i_scale.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i_scale || ORIG_REF_NAME==i_scale} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/div_gen_0/div_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/cordic_0/cordic_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/cfr_qq/cfr_qq.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfr_qq || ORIG_REF_NAME==cfr_qq} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/cfr_ii/cfr_ii.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfr_ii || ORIG_REF_NAME==cfr_ii} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DPD/fpga/dpd.gen/sources_1/bd/duc_cfr_dpd/ip/duc_cfr_dpd_cfr_0_0/duc_cfr_dpd_cfr_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'duc_cfr_dpd_cfr_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
