# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/mixer_cmpy_0/mixer_cmpy_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_cmpy_0 || ORIG_REF_NAME==mixer_cmpy_0} -quiet] -quiet

# Block Designs: bd/mixer_ddc/mixer_ddc.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_ddc || ORIG_REF_NAME==mixer_ddc} -quiet] -quiet

# IP: bd/mixer_ddc/ip/mixer_ddc_axi_bram_ctrl_0_1/mixer_ddc_axi_bram_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_ddc_axi_bram_ctrl_0_1 || ORIG_REF_NAME==mixer_ddc_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/mixer_ddc/ip/mixer_ddc_axi_dma_0_1/mixer_ddc_axi_dma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_ddc_axi_dma_0_1 || ORIG_REF_NAME==mixer_ddc_axi_dma_0_1} -quiet] -quiet

# IP: bd/mixer_ddc/ip/mixer_ddc_axis_mixer_down_0_1/mixer_ddc_axis_mixer_down_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_ddc_axis_mixer_down_0_1 || ORIG_REF_NAME==mixer_ddc_axis_mixer_down_0_1} -quiet] -quiet

# IP: ip/mixer_cmpy_0/mixer_cmpy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_cmpy_0 || ORIG_REF_NAME==mixer_cmpy_0} -quiet] -quiet

# IP: bd/mixer_ddc/ip/mixer_ddc_blk_mem_gen_0_1/mixer_ddc_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_ddc_blk_mem_gen_0_1 || ORIG_REF_NAME==mixer_ddc_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/mixer_ddc/ip/mixer_ddc_proc_sys_reset_0_1/mixer_ddc_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_ddc_proc_sys_reset_0_1 || ORIG_REF_NAME==mixer_ddc_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/mixer_ddc_smartconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_ddc_smartconnect_0_1 || ORIG_REF_NAME==mixer_ddc_smartconnect_0_1} -quiet] -quiet

# Block Designs: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/bd_bf9a.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_0/bd_bf9a_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_1/bd_bf9a_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_2/bd_bf9a_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_3/bd_bf9a_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_4/bd_bf9a_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_5/bd_bf9a_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_6/bd_bf9a_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_7/bd_bf9a_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_8/bd_bf9a_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_9/bd_bf9a_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_10/bd_bf9a_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_11/bd_bf9a_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_12/bd_bf9a_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_13/bd_bf9a_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_14/bd_bf9a_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_15/bd_bf9a_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_16/bd_bf9a_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_17/bd_bf9a_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_18/bd_bf9a_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_19/bd_bf9a_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_20/bd_bf9a_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_21/bd_bf9a_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_22/bd_bf9a_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_23/bd_bf9a_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_24/bd_bf9a_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_25/bd_bf9a_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_26/bd_bf9a_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_27/bd_bf9a_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_28/bd_bf9a_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_29/bd_bf9a_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_30/bd_bf9a_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_31/bd_bf9a_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_32/bd_bf9a_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_33/bd_bf9a_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_34/bd_bf9a_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_35/bd_bf9a_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_36/bd_bf9a_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_37/bd_bf9a_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_38/bd_bf9a_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_39/bd_bf9a_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_40/bd_bf9a_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_41/bd_bf9a_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_42/bd_bf9a_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/mixer_ddc/ip/mixer_ddc_system_ila_0_1/mixer_ddc_system_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_ddc_system_ila_0_1 || ORIG_REF_NAME==mixer_ddc_system_ila_0_1} -quiet] -quiet

# Block Designs: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_system_ila_0_1/bd_0/bd_bc78.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bc78 || ORIG_REF_NAME==bd_bc78} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_system_ila_0_1/bd_0/ip/ip_0/bd_bc78_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bc78_ila_lib_0 || ORIG_REF_NAME==bd_bc78_ila_lib_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_system_ila_0_1/bd_0/ip/ip_1/bd_bc78_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bc78_g_inst_0 || ORIG_REF_NAME==bd_bc78_g_inst_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_system_ila_0_1/bd_0/ip/ip_2/bd_bc78_slot_0_apcs_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_bc78_slot_0_apcs_0 || ORIG_REF_NAME==bd_bc78_slot_0_apcs_0} -quiet] -quiet

# IP: bd/mixer_ddc/ip/mixer_ddc_system_ila_1_1/mixer_ddc_system_ila_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_ddc_system_ila_1_1 || ORIG_REF_NAME==mixer_ddc_system_ila_1_1} -quiet] -quiet

# Block Designs: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_system_ila_1_1/bd_0/bd_7c29.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7c29 || ORIG_REF_NAME==bd_7c29} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_system_ila_1_1/bd_0/ip/ip_0/bd_7c29_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7c29_ila_lib_0 || ORIG_REF_NAME==bd_7c29_ila_lib_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_system_ila_1_1/bd_0/ip/ip_1/bd_7c29_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7c29_g_inst_0 || ORIG_REF_NAME==bd_7c29_g_inst_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_system_ila_1_1/bd_0/ip/ip_2/bd_7c29_slot_0_apcs_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_7c29_slot_0_apcs_0 || ORIG_REF_NAME==bd_7c29_slot_0_apcs_0} -quiet] -quiet

# IP: bd/mixer_ddc/ip/mixer_ddc_zynq_ultra_ps_e_0_1/mixer_ddc_zynq_ultra_ps_e_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_ddc_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==mixer_ddc_zynq_ultra_ps_e_0_1} -quiet] -quiet

# IP: bd/mixer_ddc/ip/mixer_ddc_axis_halfband_fir_0_3/mixer_ddc_axis_halfband_fir_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_ddc_axis_halfband_fir_0_3 || ORIG_REF_NAME==mixer_ddc_axis_halfband_fir_0_3} -quiet] -quiet

# IP: bd/mixer_ddc/ip/mixer_ddc_axis_decimate2_0_2/mixer_ddc_axis_decimate2_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_ddc_axis_decimate2_0_2 || ORIG_REF_NAME==mixer_ddc_axis_decimate2_0_2} -quiet] -quiet

# IP: bd/mixer_ddc/ip/mixer_ddc_axis_halfband_fir_1_2/mixer_ddc_axis_halfband_fir_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_ddc_axis_halfband_fir_1_2 || ORIG_REF_NAME==mixer_ddc_axis_halfband_fir_1_2} -quiet] -quiet

# IP: bd/mixer_ddc/ip/mixer_ddc_axis_decimate2_1_2/mixer_ddc_axis_decimate2_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_ddc_axis_decimate2_1_2 || ORIG_REF_NAME==mixer_ddc_axis_decimate2_1_2} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_axi_dma_0_1/mixer_ddc_axi_dma_0_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mixer_ddc_axi_dma_0_1 || ORIG_REF_NAME==mixer_ddc_axi_dma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_axi_dma_0_1/mixer_ddc_axi_dma_0_1_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mixer_ddc_axi_dma_0_1 || ORIG_REF_NAME==mixer_ddc_axi_dma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_blk_mem_gen_0_1/mixer_ddc_blk_mem_gen_0_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_proc_sys_reset_0_1/mixer_ddc_proc_sys_reset_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mixer_ddc_proc_sys_reset_0_1 || ORIG_REF_NAME==mixer_ddc_proc_sys_reset_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_proc_sys_reset_0_1/mixer_ddc_proc_sys_reset_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mixer_ddc_proc_sys_reset_0_1 || ORIG_REF_NAME==mixer_ddc_proc_sys_reset_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_1/bd_bf9a_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_1/bd_bf9a_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_2/bd_bf9a_arsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_3/bd_bf9a_rsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_4/bd_bf9a_awsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_5/bd_bf9a_wsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_6/bd_bf9a_bsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_10/bd_bf9a_s00a2s_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_11/bd_bf9a_sarn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_12/bd_bf9a_srn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_13/bd_bf9a_sawn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_14/bd_bf9a_swn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_15/bd_bf9a_sbn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_19/bd_bf9a_s01a2s_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_20/bd_bf9a_sarn_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_21/bd_bf9a_srn_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_25/bd_bf9a_s02a2s_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_26/bd_bf9a_sawn_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_27/bd_bf9a_swn_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_28/bd_bf9a_sbn_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_29/bd_bf9a_m00s2a_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_30/bd_bf9a_m00arn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_31/bd_bf9a_m00rn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_32/bd_bf9a_m00awn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_33/bd_bf9a_m00wn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_34/bd_bf9a_m00bn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_36/bd_bf9a_m01s2a_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_37/bd_bf9a_m01arn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_38/bd_bf9a_m01rn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_39/bd_bf9a_m01awn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_40/bd_bf9a_m01wn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/bd_0/ip/ip_41/bd_bf9a_m01bn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_smartconnect_0_1/ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bc78_ila_lib_0 || ORIG_REF_NAME==bd_bc78_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bc78_ila_lib_0 || ORIG_REF_NAME==bd_bc78_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_system_ila_0_1/bd_0/ip/ip_0/bd_bc78_ila_lib_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_system_ila_0_1/bd_0/ip/ip_2/bd_bc78_slot_0_apcs_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_bc78_slot_0_apcs_0 || ORIG_REF_NAME==bd_bc78_slot_0_apcs_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_system_ila_0_1/bd_0/bd_bc78_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_system_ila_0_1/mixer_ddc_system_ila_0_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_system_ila_1_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7c29_ila_lib_0 || ORIG_REF_NAME==bd_7c29_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_system_ila_1_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7c29_ila_lib_0 || ORIG_REF_NAME==bd_7c29_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_system_ila_1_1/bd_0/ip/ip_0/bd_7c29_ila_lib_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_system_ila_1_1/bd_0/ip/ip_2/bd_7c29_slot_0_apcs_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7c29_slot_0_apcs_0 || ORIG_REF_NAME==bd_7c29_slot_0_apcs_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_system_ila_1_1/bd_0/bd_7c29_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_system_ila_1_1/mixer_ddc_system_ila_1_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_zynq_ultra_ps_e_0_1/mixer_ddc_zynq_ultra_ps_e_0_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/ip/mixer_ddc_zynq_ultra_ps_e_0_1/mixer_ddc_zynq_ultra_ps_e_0_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==mixer_ddc_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==mixer_ddc_zynq_ultra_ps_e_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer_DDC/fpga/mixer_ddc.gen/sources_1/bd/mixer_ddc/mixer_ddc_ooc.xdc
