# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.srcs/sources_1/bd/mixer/ip/mixer_axis_mixer_down_0_0/mixer_axis_mixer_down_0_0.xci
# IP: The module: 'mixer_axis_mixer_down_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.srcs/sources_1/ip/mixer_cmpy_0/mixer_cmpy_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_cmpy_0 || ORIG_REF_NAME==mixer_cmpy_0} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_axis_mixer_down_0_0/mixer_axis_mixer_down_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mixer_axis_mixer_down_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.srcs/sources_1/bd/mixer/ip/mixer_axis_mixer_down_0_0/mixer_axis_mixer_down_0_0.xci
# IP: The module: 'mixer_axis_mixer_down_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.srcs/sources_1/ip/mixer_cmpy_0/mixer_cmpy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mixer_cmpy_0 || ORIG_REF_NAME==mixer_cmpy_0} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_axis_mixer_down_0_0/mixer_axis_mixer_down_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mixer_axis_mixer_down_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
