# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.srcs/sources_1/bd/mixer/ip/mixer_system_ila_0_1/mixer_system_ila_0_1.xci
# IP: The module: 'mixer_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_system_ila_0_1/bd_0/bd_77d6.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_77d6 || ORIG_REF_NAME==bd_77d6} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_system_ila_0_1/bd_0/ip/ip_0/bd_77d6_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_77d6_ila_lib_0 || ORIG_REF_NAME==bd_77d6_ila_lib_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_system_ila_0_1/bd_0/ip/ip_1/bd_77d6_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_77d6_g_inst_0 || ORIG_REF_NAME==bd_77d6_g_inst_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_system_ila_0_1/bd_0/ip/ip_2/bd_77d6_slot_0_apcs_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_77d6_slot_0_apcs_0 || ORIG_REF_NAME==bd_77d6_slot_0_apcs_0} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_77d6_ila_lib_0 || ORIG_REF_NAME==bd_77d6_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_77d6_ila_lib_0 || ORIG_REF_NAME==bd_77d6_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_system_ila_0_1/bd_0/ip/ip_0/bd_77d6_ila_lib_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_system_ila_0_1/bd_0/ip/ip_2/bd_77d6_slot_0_apcs_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_77d6_slot_0_apcs_0 || ORIG_REF_NAME==bd_77d6_slot_0_apcs_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_system_ila_0_1/bd_0/bd_77d6_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_system_ila_0_1/mixer_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mixer_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.srcs/sources_1/bd/mixer/ip/mixer_system_ila_0_1/mixer_system_ila_0_1.xci
# IP: The module: 'mixer_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_system_ila_0_1/bd_0/bd_77d6.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_77d6 || ORIG_REF_NAME==bd_77d6} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_system_ila_0_1/bd_0/ip/ip_0/bd_77d6_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_77d6_ila_lib_0 || ORIG_REF_NAME==bd_77d6_ila_lib_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_system_ila_0_1/bd_0/ip/ip_1/bd_77d6_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_77d6_g_inst_0 || ORIG_REF_NAME==bd_77d6_g_inst_0} -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_system_ila_0_1/bd_0/ip/ip_2/bd_77d6_slot_0_apcs_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_77d6_slot_0_apcs_0 || ORIG_REF_NAME==bd_77d6_slot_0_apcs_0} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_77d6_ila_lib_0 || ORIG_REF_NAME==bd_77d6_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_77d6_ila_lib_0 || ORIG_REF_NAME==bd_77d6_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_system_ila_0_1/bd_0/ip/ip_0/bd_77d6_ila_lib_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_system_ila_0_1/bd_0/ip/ip_2/bd_77d6_slot_0_apcs_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_77d6_slot_0_apcs_0 || ORIG_REF_NAME==bd_77d6_slot_0_apcs_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_system_ila_0_1/bd_0/bd_77d6_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/Mixer/fpga/mixer/mixer_down.gen/sources_1/bd/mixer/ip/mixer_system_ila_0_1/mixer_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mixer_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
