# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DPD/fpga/dpd.srcs/sources_1/bd/duc_cfr_dpd/ip/duc_cfr_dpd_dpd_0_0/duc_cfr_dpd_dpd_0_0.xci
# IP: The module: 'duc_cfr_dpd_dpd_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DPD/fpga/dpd.srcs/sources_1/ip/term_cmpy_0/term_cmpy_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==term_cmpy_0 || ORIG_REF_NAME==term_cmpy_0} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DPD/fpga/dpd.srcs/sources_1/ip/basic_mult/basic_mult.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==basic_mult || ORIG_REF_NAME==basic_mult} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DPD/fpga/dpd.srcs/sources_1/ip/power4_mult/power4_mult.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==power4_mult || ORIG_REF_NAME==power4_mult} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DPD/fpga/dpd.srcs/sources_1/ip/power_mult1/power_mult1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==power_mult1 || ORIG_REF_NAME==power_mult1} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DPD/fpga/dpd.srcs/sources_1/ip/power_mult/power_mult.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==power_mult || ORIG_REF_NAME==power_mult} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DPD/fpga/dpd.gen/sources_1/bd/duc_cfr_dpd/ip/duc_cfr_dpd_dpd_0_0/duc_cfr_dpd_dpd_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'duc_cfr_dpd_dpd_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DPD/fpga/dpd.srcs/sources_1/bd/duc_cfr_dpd/ip/duc_cfr_dpd_dpd_0_0/duc_cfr_dpd_dpd_0_0.xci
# IP: The module: 'duc_cfr_dpd_dpd_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DPD/fpga/dpd.srcs/sources_1/ip/term_cmpy_0/term_cmpy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==term_cmpy_0 || ORIG_REF_NAME==term_cmpy_0} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DPD/fpga/dpd.srcs/sources_1/ip/basic_mult/basic_mult.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==basic_mult || ORIG_REF_NAME==basic_mult} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DPD/fpga/dpd.srcs/sources_1/ip/power4_mult/power4_mult.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==power4_mult || ORIG_REF_NAME==power4_mult} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DPD/fpga/dpd.srcs/sources_1/ip/power_mult1/power_mult1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==power_mult1 || ORIG_REF_NAME==power_mult1} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DPD/fpga/dpd.srcs/sources_1/ip/power_mult/power_mult.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==power_mult || ORIG_REF_NAME==power_mult} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DPD/fpga/dpd.gen/sources_1/bd/duc_cfr_dpd/ip/duc_cfr_dpd_dpd_0_0/duc_cfr_dpd_dpd_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'duc_cfr_dpd_dpd_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
