# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ddc/ddc.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddc || ORIG_REF_NAME==ddc} -quiet] -quiet

# IP: bd/ddc/ip/ddc_zynq_ultra_ps_e_0_0/ddc_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddc_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==ddc_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/ddc/ip/ddc_proc_sys_reset_0_0/ddc_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddc_proc_sys_reset_0_0 || ORIG_REF_NAME==ddc_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ddc/ip/ddc_smartconnect_0_0/ddc_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddc_smartconnect_0_0 || ORIG_REF_NAME==ddc_smartconnect_0_0} -quiet] -quiet

# IP: bd/ddc/ip/ddc_axi_bram_ctrl_0_0/ddc_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddc_axi_bram_ctrl_0_0 || ORIG_REF_NAME==ddc_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/ddc/ip/ddc_blk_mem_gen_0_0/ddc_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddc_blk_mem_gen_0_0 || ORIG_REF_NAME==ddc_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/ddc/ip/ddc_axi_dma_0_0/ddc_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddc_axi_dma_0_0 || ORIG_REF_NAME==ddc_axi_dma_0_0} -quiet] -quiet

# IP: bd/ddc/ip/ddc_axis_decimate2_0_0/ddc_axis_decimate2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddc_axis_decimate2_0_0 || ORIG_REF_NAME==ddc_axis_decimate2_0_0} -quiet] -quiet

# IP: bd/ddc/ip/ddc_axis_halfband_fir_0_0/ddc_axis_halfband_fir_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddc_axis_halfband_fir_0_0 || ORIG_REF_NAME==ddc_axis_halfband_fir_0_0} -quiet] -quiet

# IP: bd/ddc/ip/ddc_axis_decimate2_0_1/ddc_axis_decimate2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddc_axis_decimate2_0_1 || ORIG_REF_NAME==ddc_axis_decimate2_0_1} -quiet] -quiet

# IP: bd/ddc/ip/ddc_axis_halfband_fir_0_1/ddc_axis_halfband_fir_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddc_axis_halfband_fir_0_1 || ORIG_REF_NAME==ddc_axis_halfband_fir_0_1} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Uplink/fpga/ddc/ddc.gen/sources_1/bd/ddc/ddc_ooc.xdc
