# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.srcs/sources_1/ip/tb_axis_data_fifo_0/tb_axis_data_fifo_0.xci
# IP: The module: 'tb_axis_data_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/ip/tb_axis_data_fifo_0/tb_axis_data_fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tb_axis_data_fifo_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.srcs/sources_1/ip/tb_axis_data_fifo_0/tb_axis_data_fifo_0.xci
# IP: The module: 'tb_axis_data_fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DUC/duc/duc.gen/sources_1/ip/tb_axis_data_fifo_0/tb_axis_data_fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tb_axis_data_fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
