# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/q_scale/q_scale.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==q_scale || ORIG_REF_NAME==q_scale} -quiet] -quiet

# IP: ip/i_scale/i_scale.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i_scale || ORIG_REF_NAME==i_scale} -quiet] -quiet

# IP: ip/div_gen_0/div_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: ip/cordic_0/cordic_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# IP: ip/cfr_qq/cfr_qq.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfr_qq || ORIG_REF_NAME==cfr_qq} -quiet] -quiet

# IP: ip/cfr_ii/cfr_ii.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfr_ii || ORIG_REF_NAME==cfr_ii} -quiet] -quiet

# Block Designs: bd/duc_cfr/duc_cfr.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr || ORIG_REF_NAME==duc_cfr} -quiet] -quiet

# IP: bd/duc_cfr/ip/duc_cfr_axi_bram_ctrl_0_0/duc_cfr_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_axi_bram_ctrl_0_0 || ORIG_REF_NAME==duc_cfr_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/duc_cfr/ip/duc_cfr_axi_dma_0_0/duc_cfr_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_axi_dma_0_0 || ORIG_REF_NAME==duc_cfr_axi_dma_0_0} -quiet] -quiet

# IP: bd/duc_cfr/ip/duc_cfr_blk_mem_gen_0_0/duc_cfr_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_blk_mem_gen_0_0 || ORIG_REF_NAME==duc_cfr_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/duc_cfr/ip/duc_cfr_proc_sys_reset_0_0/duc_cfr_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_proc_sys_reset_0_0 || ORIG_REF_NAME==duc_cfr_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/duc_cfr_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_smartconnect_0_0 || ORIG_REF_NAME==duc_cfr_smartconnect_0_0} -quiet] -quiet

# Block Designs: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/bd_1c3c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_0/bd_1c3c_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_1/bd_1c3c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_2/bd_1c3c_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_3/bd_1c3c_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_4/bd_1c3c_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_5/bd_1c3c_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_6/bd_1c3c_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_7/bd_1c3c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_8/bd_1c3c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_9/bd_1c3c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_10/bd_1c3c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_11/bd_1c3c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_12/bd_1c3c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_13/bd_1c3c_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_14/bd_1c3c_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_15/bd_1c3c_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_16/bd_1c3c_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_17/bd_1c3c_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_18/bd_1c3c_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_19/bd_1c3c_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_20/bd_1c3c_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_21/bd_1c3c_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_22/bd_1c3c_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_23/bd_1c3c_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_24/bd_1c3c_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_25/bd_1c3c_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_26/bd_1c3c_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_27/bd_1c3c_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_28/bd_1c3c_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_29/bd_1c3c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_30/bd_1c3c_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_31/bd_1c3c_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_32/bd_1c3c_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_33/bd_1c3c_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_34/bd_1c3c_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_35/bd_1c3c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_36/bd_1c3c_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_37/bd_1c3c_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_38/bd_1c3c_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_39/bd_1c3c_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_40/bd_1c3c_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_41/bd_1c3c_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_42/bd_1c3c_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/duc_cfr/ip/duc_cfr_zynq_ultra_ps_e_0_0/duc_cfr_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==duc_cfr_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/duc_cfr/ip/duc_cfr_axis_upsample_0_0/duc_cfr_axis_upsample_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_axis_upsample_0_0 || ORIG_REF_NAME==duc_cfr_axis_upsample_0_0} -quiet] -quiet

# IP: bd/duc_cfr/ip/duc_cfr_halfband_fir_0_0/duc_cfr_halfband_fir_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_halfband_fir_0_0 || ORIG_REF_NAME==duc_cfr_halfband_fir_0_0} -quiet] -quiet

# IP: bd/duc_cfr/ip/duc_cfr_halfband_fir_0_1/duc_cfr_halfband_fir_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_halfband_fir_0_1 || ORIG_REF_NAME==duc_cfr_halfband_fir_0_1} -quiet] -quiet

# IP: bd/duc_cfr/ip/duc_cfr_axis_upsample_0_1/duc_cfr_axis_upsample_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_axis_upsample_0_1 || ORIG_REF_NAME==duc_cfr_axis_upsample_0_1} -quiet] -quiet

# IP: bd/duc_cfr/ip/duc_cfr_cfr_0_0/duc_cfr_cfr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_cfr_0_0 || ORIG_REF_NAME==duc_cfr_cfr_0_0} -quiet] -quiet

# IP: ip/q_scale/q_scale.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==q_scale || ORIG_REF_NAME==q_scale} -quiet] -quiet

# IP: ip/i_scale/i_scale.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i_scale || ORIG_REF_NAME==i_scale} -quiet] -quiet

# IP: ip/div_gen_0/div_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: ip/cordic_0/cordic_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# IP: ip/cfr_qq/cfr_qq.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfr_qq || ORIG_REF_NAME==cfr_qq} -quiet] -quiet

# IP: ip/cfr_ii/cfr_ii.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfr_ii || ORIG_REF_NAME==cfr_ii} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_axi_dma_0_0/duc_cfr_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==duc_cfr_axi_dma_0_0 || ORIG_REF_NAME==duc_cfr_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_axi_dma_0_0/duc_cfr_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==duc_cfr_axi_dma_0_0 || ORIG_REF_NAME==duc_cfr_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_blk_mem_gen_0_0/duc_cfr_blk_mem_gen_0_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_proc_sys_reset_0_0/duc_cfr_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==duc_cfr_proc_sys_reset_0_0 || ORIG_REF_NAME==duc_cfr_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_proc_sys_reset_0_0/duc_cfr_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==duc_cfr_proc_sys_reset_0_0 || ORIG_REF_NAME==duc_cfr_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_1/bd_1c3c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_1/bd_1c3c_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_2/bd_1c3c_arsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_3/bd_1c3c_rsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_4/bd_1c3c_awsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_5/bd_1c3c_wsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_6/bd_1c3c_bsw_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_10/bd_1c3c_s00a2s_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_11/bd_1c3c_sarn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_12/bd_1c3c_srn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_13/bd_1c3c_sawn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_14/bd_1c3c_swn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_15/bd_1c3c_sbn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_19/bd_1c3c_s01a2s_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_20/bd_1c3c_sarn_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_21/bd_1c3c_srn_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_25/bd_1c3c_s02a2s_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_26/bd_1c3c_sawn_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_27/bd_1c3c_swn_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_28/bd_1c3c_sbn_1_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_29/bd_1c3c_m00s2a_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_30/bd_1c3c_m00arn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_31/bd_1c3c_m00rn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_32/bd_1c3c_m00awn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_33/bd_1c3c_m00wn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_34/bd_1c3c_m00bn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_36/bd_1c3c_m01s2a_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_37/bd_1c3c_m01arn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_38/bd_1c3c_m01rn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_39/bd_1c3c_m01awn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_40/bd_1c3c_m01wn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/bd_0/ip/ip_41/bd_1c3c_m01bn_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_smartconnect_0_0/ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_zynq_ultra_ps_e_0_0/duc_cfr_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/ip/duc_cfr_zynq_ultra_ps_e_0_0/duc_cfr_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==duc_cfr_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==duc_cfr_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/CFR.gen/sources_1/bd/duc_cfr/duc_cfr_ooc.xdc
