# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/q_scale/q_scale.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==q_scale || ORIG_REF_NAME==q_scale} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/i_scale/i_scale.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i_scale || ORIG_REF_NAME==i_scale} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/div_gen_0/div_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/cordic_0/cordic_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/cfr_qq/cfr_qq.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfr_qq || ORIG_REF_NAME==cfr_qq} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/cfr_ii/cfr_ii.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfr_ii || ORIG_REF_NAME==cfr_ii} -quiet] -quiet

# IP: ip/term_cmpy_0/term_cmpy_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==term_cmpy_0 || ORIG_REF_NAME==term_cmpy_0} -quiet] -quiet

# IP: ip/basic_mult/basic_mult.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==basic_mult || ORIG_REF_NAME==basic_mult} -quiet] -quiet

# IP: ip/power4_mult/power4_mult.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==power4_mult || ORIG_REF_NAME==power4_mult} -quiet] -quiet

# IP: ip/power_mult1/power_mult1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==power_mult1 || ORIG_REF_NAME==power_mult1} -quiet] -quiet

# IP: ip/power_mult/power_mult.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==power_mult || ORIG_REF_NAME==power_mult} -quiet] -quiet

# Block Designs: bd/duc_cfr_dpd/duc_cfr_dpd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_dpd || ORIG_REF_NAME==duc_cfr_dpd} -quiet] -quiet

# IP: bd/duc_cfr_dpd/ip/duc_cfr_dpd_axi_bram_ctrl_0_0/duc_cfr_dpd_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_dpd_axi_bram_ctrl_0_0 || ORIG_REF_NAME==duc_cfr_dpd_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/duc_cfr_dpd/ip/duc_cfr_dpd_axi_dma_0_0/duc_cfr_dpd_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_dpd_axi_dma_0_0 || ORIG_REF_NAME==duc_cfr_dpd_axi_dma_0_0} -quiet] -quiet

# IP: bd/duc_cfr_dpd/ip/duc_cfr_dpd_axis_upsample_0_0/duc_cfr_dpd_axis_upsample_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_dpd_axis_upsample_0_0 || ORIG_REF_NAME==duc_cfr_dpd_axis_upsample_0_0} -quiet] -quiet

# IP: bd/duc_cfr_dpd/ip/duc_cfr_dpd_axis_upsample_1_0/duc_cfr_dpd_axis_upsample_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_dpd_axis_upsample_1_0 || ORIG_REF_NAME==duc_cfr_dpd_axis_upsample_1_0} -quiet] -quiet

# IP: bd/duc_cfr_dpd/ip/duc_cfr_dpd_blk_mem_gen_0_0/duc_cfr_dpd_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_dpd_blk_mem_gen_0_0 || ORIG_REF_NAME==duc_cfr_dpd_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/duc_cfr_dpd/ip/duc_cfr_dpd_cfr_0_0/duc_cfr_dpd_cfr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_dpd_cfr_0_0 || ORIG_REF_NAME==duc_cfr_dpd_cfr_0_0} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/q_scale/q_scale.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==q_scale || ORIG_REF_NAME==q_scale} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/i_scale/i_scale.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==i_scale || ORIG_REF_NAME==i_scale} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/div_gen_0/div_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/cordic_0/cordic_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/cfr_qq/cfr_qq.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfr_qq || ORIG_REF_NAME==cfr_qq} -quiet] -quiet

# IP: D:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/CFR/fpga/CFR.srcs/sources_1/ip/cfr_ii/cfr_ii.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cfr_ii || ORIG_REF_NAME==cfr_ii} -quiet] -quiet

# IP: bd/duc_cfr_dpd/ip/duc_cfr_dpd_halfband_fir_0_0/duc_cfr_dpd_halfband_fir_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_dpd_halfband_fir_0_0 || ORIG_REF_NAME==duc_cfr_dpd_halfband_fir_0_0} -quiet] -quiet

# IP: bd/duc_cfr_dpd/ip/duc_cfr_dpd_halfband_fir_1_0/duc_cfr_dpd_halfband_fir_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_dpd_halfband_fir_1_0 || ORIG_REF_NAME==duc_cfr_dpd_halfband_fir_1_0} -quiet] -quiet

# IP: bd/duc_cfr_dpd/ip/duc_cfr_dpd_proc_sys_reset_0_0/duc_cfr_dpd_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_dpd_proc_sys_reset_0_0 || ORIG_REF_NAME==duc_cfr_dpd_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/duc_cfr_dpd/ip/duc_cfr_dpd_smartconnect_0_0/duc_cfr_dpd_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_dpd_smartconnect_0_0 || ORIG_REF_NAME==duc_cfr_dpd_smartconnect_0_0} -quiet] -quiet

# IP: bd/duc_cfr_dpd/ip/duc_cfr_dpd_zynq_ultra_ps_e_0_0/duc_cfr_dpd_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_dpd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==duc_cfr_dpd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/duc_cfr_dpd/ip/duc_cfr_dpd_ila_0_0/duc_cfr_dpd_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_dpd_ila_0_0 || ORIG_REF_NAME==duc_cfr_dpd_ila_0_0} -quiet] -quiet

# IP: bd/duc_cfr_dpd/ip/duc_cfr_dpd_ila_0_2/duc_cfr_dpd_ila_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_dpd_ila_0_2 || ORIG_REF_NAME==duc_cfr_dpd_ila_0_2} -quiet] -quiet

# IP: bd/duc_cfr_dpd/ip/duc_cfr_dpd_system_ila_0_0/duc_cfr_dpd_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_dpd_system_ila_0_0 || ORIG_REF_NAME==duc_cfr_dpd_system_ila_0_0} -quiet] -quiet

# IP: bd/duc_cfr_dpd/ip/duc_cfr_dpd_dpd_0_0/duc_cfr_dpd_dpd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_cfr_dpd_dpd_0_0 || ORIG_REF_NAME==duc_cfr_dpd_dpd_0_0} -quiet] -quiet

# IP: ip/term_cmpy_0/term_cmpy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==term_cmpy_0 || ORIG_REF_NAME==term_cmpy_0} -quiet] -quiet

# IP: ip/basic_mult/basic_mult.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==basic_mult || ORIG_REF_NAME==basic_mult} -quiet] -quiet

# IP: ip/power4_mult/power4_mult.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==power4_mult || ORIG_REF_NAME==power4_mult} -quiet] -quiet

# IP: ip/power_mult1/power_mult1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==power_mult1 || ORIG_REF_NAME==power_mult1} -quiet] -quiet

# IP: ip/power_mult/power_mult.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==power_mult || ORIG_REF_NAME==power_mult} -quiet] -quiet

# XDC: d:/FPGA/Vivaldo Project/Digital_Font_End_LTE/Downlink/DPD/fpga/dpd.gen/sources_1/bd/duc_cfr_dpd/duc_cfr_dpd_ooc.xdc
